version: "2.2"
services:

# zookeeper

  zool:
    image: 'zookeeper:3.4.9'
    restart: unless-stopped
    hostname: zool
    ports:
    - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zool:2888:3888
  
  ### Kafka ###

  kafka-cp-kafka-headless:
    image: confluentinc/cp-kafka:5.0.0 # 什么要用 cp-kafka 镜像，在 readme.md 有描述
    hostname: kafka-cp-kafka-headless
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-cp-kafka-headless:9092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_EXTERNAL:PLAINTEXT,LISTENER_DOCKER_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zool:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG$J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zool

### Schema Resistry #### 为什么需要 Scheme Registry ，也在 readme.md 文件有描述
## Schema Registry 启动后马上退出
  schema-registry:
    entrypoint: ["echo","Optional component. Remove this line (entrypoint) to enable"] ##说明性语句?
    image: confluentinc/cp-schema-registry:5.2.1
    hostname: schema-registry
    ports:
      - "18081:18081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-cp-kafka-headless:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:18081,http://schema-registry:28081
    depends_on:
      - zool
      - kafka-cp-kafka-headless

### Schema Registry UI ###
## Schema Registry 启动后马上退出
  schema-registry-ui:
    entrypoint: ["echo","Optional component. Remove this line (entrypoint) to enable"]
    image: landoop/schema-registry-ui:0.9.4
    hostname: schema-registry-ui
    ports:
      - "8001:8000"
    environment:
      SCHEMAREGISTRY_URL: http://schema-registry:28081/
      PROXY: "true"
    depends_on:
      - schema-registry

### Flink Job Cluster

  flink-master:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink-job-fraud-swj:latest}
    ports:
      - "8081:8081"
      ## rules-generator 先用 static
    command: job-cluster --job-classname com.swj.sensors.flink_study.fraud_detection.dynamic_rules.Main -Djobmanager.rpc.address=flink-master -Dparallelism.default=2 --data-source kafka --rules-source kafka --alerts-sink kafka --rules-sink kafka --rules-export-sink kafka --latency-sink kafka --kafka-host kafka-cp-kafka-headless --kafka-port 9092
    depends_on:
      - kafka-cp-kafka-headless

  flink-task-manager:
    image: ${FLINK_DOCKER_IMAGE_NAME:-flink-job-fraud-swj:latest}
    depends_on:
      - kafka-cp-kafka-headless
    command: task-manager -Djobmanager.rpc.address=flink-master
    scale: ${DEFAULT_PARALLELISM:-2}